import type { Species } from '../types';

/**
 * Hand-designed beasts. Keys are permanent: saves store them, so never
 * rename a key once it has shipped (rename the display name instead).
 */
export const CORE: Record<string, Species> = {
  cindermaw:{name:'Cindermaw',el:'pyre',rarity:'common',body:'brute',c1:'#C8472A',c2:'#F4A24A',eye:'#FFE7A3',hp:120,atk:14,spd:1.0,horns:2,special:'Magma Bite',
    forms:["Cindermaw", "Scorchmaw", "Infernomaw"],
    look:"A round, stocky little fire beast with molten red-orange skin, a warm ember-orange belly, two curved bone-white horns, a wide grin full of small sharp teeth, glowing pale-yellow eyes under angry brows, and short stubby arms. Hot-headed and grumpy. Fire element.",
    evoLooks:["Noticeably bigger and more muscular. Four horns instead of two. Glowing lava cracks across the skin, and wisps of smoke from its nostrils.","A hulking, powerful version. Six horns forming a crown, plates of cooled obsidian armor with molten seams, a mane of flame, small embers orbiting it, and a strong fiery aura."]},
  ashwing:{name:'Ashwing',el:'pyre',rarity:'rare',body:'wisp',c1:'#D9582A',c2:'#FFD36B',eye:'#FFF8E6',hp:98,atk:19,spd:1.2,eyes:1,special:'Cinder Storm',
    forms:["Ashwing", "Cinderwing", "Solwing"],
    look:"A living flame spirit with a teardrop body of golden-yellow fire fading to orange at the edges, three flickering flame tips on top, one large friendly cyclops eye, two small floating flame hands, and a trail of embers beneath it instead of legs. Playful and quick. Fire element.",
    evoLooks:["Grows a pair of wings made of flame, and two small fireballs orbit it. The fire burns brighter and hotter.","A radiant sun-fire spirit with three eyes, large sweeping flame wings, and a blazing solar halo behind its head, with gold rune symbols floating around it."]},
  vhal:{name:'Vhal the Kilnborn',el:'pyre',rarity:'epic',body:'brute',c1:'#8E1F2A',c2:'#FF7A3D',eye:'#FFF1B8',hp:150,atk:22,spd:1.0,horns:4,special:'Kilnheart Eruption',
    forms:["Vhal the Kilnborn", "Vhal, Forge Tyrant", "Vhal, Heart of the Kiln"],
    look:"A towering kiln demon with a deep crimson body, a glowing ember-orange chest, four large swept-back horns, forge-like cracks glowing across its hide, massive fists and a fierce, noble expression. Legendary and intimidating. Fire element.",
    evoLooks:["Plated in dark obsidian armor with molten seams, six horns, fists like forge hammers, and heat shimmering off its body.","A colossal form with an open furnace in its chest showing a blazing core, a crown of horns, gold rune symbols orbiting it, and a powerful red-gold aura."]},
  brambleback:{name:'Brambleback',el:'thorn',rarity:'common',body:'brute',c1:'#4F7A3A',c2:'#A7D46F',eye:'#F6F1B0',hp:140,atk:12,spd:0.9,horns:0,spikes:true,special:'Briar Slam',
    forms:["Brambleback", "Thornhide", "Elderbramble"],
    look:"A round, sturdy forest beast with a leafy green body, a pale green belly, and a back covered in sharp pale thorny spikes. No horns. A grumpy toothy grin, pale yellow eyes and short stubby arms. Stubborn and tough. Nature element.",
    evoLooks:["Bigger, with longer and more numerous thorns and two horns of twisted wood. Small leaves sprout along its back.","An ancient guardian with bark-armored skin, a crown of flowering thorns, a mossy beard, tiny glowing mushrooms growing on its shoulders and a green aura."]},
  mosswraith:{name:'Mosswraith',el:'thorn',rarity:'rare',body:'wisp',c1:'#3F6E4A',c2:'#9FDB8A',eye:'#E9FFD8',hp:106,atk:17,spd:1.15,eyes:1,special:'Spore Veil',
    forms:["Mosswraith", "Bloomwraith", "Verdant Revenant"],
    look:"A floating forest spirit made of glowing moss, with a soft green teardrop body, one large gentle eye, two small leaf-like floating hands and drifting spores trailing beneath it. Calm and mysterious. Nature element.",
    evoLooks:["Flowers bloom across its body and glowing pollen motes orbit it. The glow brightens.","A luminous forest phantom with three eyes, a crown of flowers and vines, long trailing tendrils of moss, and gold rune symbols orbiting it."]},
  ysra:{name:'Ysra of the Hedge',el:'thorn',rarity:'epic',body:'serpent',c1:'#2F5E36',c2:'#C6E36A',eye:'#FFF3A8',hp:145,atk:21,spd:1.1,crown:true,special:'Crown of Thorns',
    forms:["Ysra of the Hedge", "Ysra, Thorn Regent", "Ysra, Queen Eternal"],
    look:"A regal serpent made of vines, with deep green scales, a lime-yellow belly, leaf-shaped fins on the sides of its head and a small crown of pale thorns. It rises from a coiled base. Proud and elegant. Nature element.",
    evoLooks:["Larger leaf fins, blooming roses along its coils and a taller thorn crown.","A towering serpent queen with a golden crown of thorns, flowers blooming all along its body, a flowing leaf mane, and gold rune symbols orbiting it."]},
  tidecoil:{name:'Tidecoil',el:'tide',rarity:'common',body:'serpent',c1:'#2A6FA3',c2:'#7FD0F0',eye:'#E8FBFF',hp:118,atk:14,spd:1.05,special:'Undertow',
    forms:["Tidecoil", "Rivercoil", "Leviacoil"],
    look:"A small sea serpent with ocean-blue scales and a light aqua belly, coiled up on itself, with fin-shaped ears, big curious eyes and a little smile. Friendly and curious. Water element.",
    evoLooks:["Longer and larger with bigger flowing fins and ribbons of water swirling around it.","A leviathan-like sea serpent with a crown of coral, glowing blue markings, rings of water circling it and gold rune symbols orbiting it."]},
  brinehound:{name:'Brinehound',el:'tide',rarity:'rare',body:'brute',c1:'#245C7E',c2:'#6FC3D9',eye:'#DFF8FF',hp:132,atk:17,spd:1.0,horns:0,fins:true,special:'Riptide Maul',
    forms:["Brinehound", "Stormhound", "Tempest Hound"],
    look:"A stocky sea-dog beast with a deep teal body, a lighter aqua belly, fin-shaped ears, a few barnacles on its shoulders and a toothy grin. Loyal and scrappy. Water element.",
    evoLooks:["Bigger, with coral-like horns, a mane of sea foam and larger fins.","A huge tempest beast with a swirling whirlpool mane, glowing blue markings, crashing water around its feet and gold rune symbols orbiting it."]},
  mawdeep:{name:'Mawdeep',el:'tide',rarity:'epic',body:'wisp',c1:'#1B3F73',c2:'#5FB4F0',eye:'#F0FAFF',hp:135,atk:23,spd:1.1,eyes:3,special:'Abyssal Call',
    forms:["Mawdeep", "Trenchmaw", "Abyssal Mawdeep"],
    look:"A floating abyssal water spirit with a deep navy body that glows bright blue at the edges, three eyes (one large and two small), bioluminescent spots, and ghostly trailing wisps beneath it. Eerie and ancient. Water element.",
    evoLooks:["Grows a glowing anglerfish lure from its head, and more bioluminescent spots and orbiting water droplets.","An enormous deep-sea spirit with a wide glowing maw, rows of luminous eyes, dark flowing tendrils and gold rune symbols orbiting it."]},
  shardling:{name:'Shardling',el:'frost',rarity:'common',body:'golem',c1:'#5E9FC0',c2:'#CFF1FF',eye:'#EFFFFF',hp:135,atk:13,spd:0.9,special:'Frostbite Volley',
    forms:["Shardling", "Glacierguard", "Permafrost Colossus"],
    look:"A small, blocky ice golem made of frosted blue ice, with a glowing white diamond-shaped core in its chest, sharp ice crystals growing from its shoulders, a narrow glowing eye slit, and big heavy fists. Sturdy and quiet. Ice element.",
    evoLooks:["Taller and broader, with more ice crystals, thick frost armor and a cold mist rolling off it.","A massive glacier fortress with a crown of towering ice crystals, a blazing white core, snow drifting around it and gold rune symbols orbiting it."]},
  rimewing:{name:'Rimewing',el:'frost',rarity:'rare',body:'avian',c1:'#4F8FB8',c2:'#D8F4FF',eye:'#F2FEFF',hp:104,atk:18,spd:1.2,special:'Glacial Lance',
    forms:["Rimewing", "Hoarfrost Roc", "Aurora Roc"],
    look:"A round frost bird with pale blue feathers tipped in white, an icy crest, a small gold beak, big gentle eyes, and wings spread wide. Graceful. Ice element.",
    evoLooks:["Larger wings with icicle-tipped feathers and a taller crystal crest.","A majestic roc with aurora-colored light trailing from its wings, a crystal crest, glittering frost and gold rune symbols orbiting it."]},
  voltfinch:{name:'Voltfinch',el:'storm',rarity:'common',body:'avian',c1:'#C9A21E',c2:'#FFF08A',eye:'#FFFFFF',hp:100,atk:16,spd:1.25,special:'Spark Dive',
    forms:["Voltfinch", "Arcfinch", "Thunderbird"],
    look:"A small round lightning finch with golden-yellow feathers, a spiky electric crest, big bright eyes, and little sparks crackling around its wings. Hyperactive and cheeky. Lightning element.",
    evoLooks:["Bigger, with lightning-tipped wings, a larger crest and arcs of electricity between its feathers.","A majestic storm bird with wings made of thunderclouds crackling with lightning, a blazing crest and gold rune symbols orbiting it."]},
  thunderhorn:{name:'Thunderhorn',el:'storm',rarity:'rare',body:'brute',c1:'#5A4A8C',c2:'#F2DC5D',eye:'#FFF6C2',hp:130,atk:18,spd:1.0,horns:2,special:'Skybreaker',
    forms:["Thunderhorn", "Stormcaller", "Tempest Titan"],
    look:"A stocky storm beast with an indigo-purple body, glowing yellow lightning-bolt markings, two horns crackling with electricity, and a fierce toothy grin. Loud and bold. Lightning element.",
    evoLooks:["Four horns acting like lightning rods, a mane of dark storm clouds and more intense lightning markings.","A hulking titan with a crown of lightning, storm clouds swirling around its shoulders, glowing eyes and gold rune symbols orbiting it."]},
  cobbleguard:{name:'Cobbleguard',el:'stone',rarity:'common',body:'golem',c1:'#7A6246',c2:'#C9AE86',eye:'#FFB35C',hp:150,atk:11,spd:0.85,special:'Rockfall',
    forms:["Cobbleguard", "Bastion", "Mountainheart"],
    look:"A small stone golem made of rough brown cobblestones, with a glowing amber core in its chest, a glowing amber eye slit, rough crystals on its shoulders and big blocky fists. Dependable and slow. Earth element.",
    evoLooks:["Built like a small fortress, with thicker stone plates, bigger shoulder crystals and moss in the cracks.","A mountain-sized golem with rocky peaks rising from its shoulders, a magma-amber core, pebbles floating around it and gold rune symbols orbiting it."]},
  quarryback:{name:'Quarryback',el:'stone',rarity:'rare',body:'brute',c1:'#6B5A48',c2:'#B8A07E',eye:'#FFD28A',hp:150,atk:16,spd:0.9,horns:0,spikes:true,special:'Landslide',
    forms:["Quarryback", "Boulderhide", "Tectonic Behemoth"],
    look:"A round, armadillo-like rock beast with a gray-brown stony hide, a back covered in jagged rock spikes, pale amber eyes and a toothy grin. Tough and grumpy. Earth element.",
    evoLooks:["Larger, with thick boulder-like armor plates and two stone horns.","A behemoth with shifting tectonic plates across its back, glowing amber cracks between them and gold rune symbols orbiting it."]},
  zephyrkit:{name:'Zephyrkit',el:'gale',rarity:'common',body:'avian',c1:'#5FA88A',c2:'#DFF7EA',eye:'#FFFFFF',hp:105,atk:14,spd:1.3,special:'Gust Spiral',
    forms:["Zephyrkit", "Windreaver", "Skyrender"],
    look:"A light mint-green bird with swirling feathers, a cream-white chest, a curling crest, a small gold beak and a cheerful face, surrounded by little visible wind swirls. Carefree. Wind element.",
    evoLooks:["Larger, with swept-back blade-like wings and stronger wind currents curling around it.","A grand sky bird with long flowing wings, visible spiraling wind currents, a tall crest and gold rune symbols orbiting it."]},
  galewyrm:{name:'Galewyrm',el:'gale',rarity:'rare',body:'serpent',c1:'#4E9A7E',c2:'#C8F0DC',eye:'#F4FFF9',hp:118,atk:18,spd:1.15,special:'Cyclone Coil',
    forms:["Galewyrm", "Squallwyrm", "Cyclone Wyrm"],
    look:"An airy serpent with mint-green scales, a pale cream belly, wing-like fins on its head and wisps of wind trailing from its body. Swift and aloof. Wind element.",
    evoLooks:["Longer and larger, with bigger wing fins and a small whirlwind around its coils.","A serpent riding a spiraling cyclone, with a crown of feathers, long wing-fins and gold rune symbols orbiting it."]},
  lumenfawn:{name:'Lumenfawn',el:'radiant',rarity:'rare',body:'brute',c1:'#D9B45A',c2:'#FFF3C4',eye:'#FFFFFF',hp:125,atk:18,spd:1.05,horns:2,special:'Dawnbeam',
    forms:["Lumenfawn", "Dawnstag", "Solar Hart"],
    look:"A gentle light beast shaped like a young fawn, with soft golden fur, a pale cream belly, small glowing antler-horns, bright white eyes and a warm golden glow. Kind and serene. Light element.",
    evoLooks:["Larger, with a full set of branching antlers and a soft halo behind its head.","A radiant stag with sunburst antlers, golden light pouring from its body, and gold rune symbols orbiting it."]},
  seraphel:{name:'Seraphel',el:'radiant',rarity:'epic',body:'avian',c1:'#E0B84E',c2:'#FFF8DD',eye:'#FFFFFF',hp:140,atk:23,spd:1.15,special:'Judgement Light',
    forms:["Seraphel", "Seraphel, Bright Wing", "Seraphel, Crown of Dawn"],
    look:"An angelic golden bird with cream and gold feathers, a halo-shaped crest, large luminous wings, bright white eyes and a noble expression. Legendary and holy. Light element.",
    evoLooks:["Four wings instead of two, a brighter halo, and feathers edged in light.","Six radiant wings, a crown shaped like the rising sun, beams of light behind it, and gold rune symbols orbiting it."]},
  duskmote:{name:'Duskmote',el:'umbral',rarity:'rare',body:'wisp',c1:'#3A2560',c2:'#9A6BD6',eye:'#E6D6FF',hp:108,atk:19,spd:1.15,eyes:1,special:'Night Hollow',
    forms:["Duskmote", "Gloamwisp", "Eclipse Shade"],
    look:"A floating shadow wisp with a dark purple flame-like body fading to violet at the edges, one glowing lavender eye, small shadowy floating hands and dark wisps trailing beneath it. Mischievous. Dark element.",
    evoLooks:["Larger and darker, with two small orbs of violet light circling it and longer shadow trails.","A shade with three glowing eyes, a black eclipse halo ringed in violet light, and gold rune symbols orbiting it."]},
  nyxhollow:{name:'Nyxhollow',el:'umbral',rarity:'epic',body:'golem',c1:'#2A1C44',c2:'#8C5AD8',eye:'#D9B8FF',hp:160,atk:21,spd:0.95,special:'Void Collapse',
    forms:["Nyxhollow", "Nyxhollow, Void Warden", "Nyxhollow, End of Stars"],
    look:"An obsidian void golem with a near-black purple body, a glowing violet diamond core in its chest, violet crystals on its shoulders, a glowing violet eye slit, and heavy blocky fists. Ominous and silent. Dark element.",
    evoLooks:["Taller, with more violet crystals and dark armor plates, with shadow flowing off it.","A colossal golem whose body cracks open to reveal a starry night sky inside, with a crown of void crystals and gold rune symbols orbiting it."]},
  // ---------- Pyre ----------
  blazelynx:{name:'Blazelynx',el:'pyre',rarity:'rare',body:'beast',c1:'#D8572A',c2:'#FFC15E',eye:'#FFF4C8',hp:108,atk:18,spd:1.2,tail:'flame',pattern:'stripes',special:'Pounce of Embers',
    forms:['Blazelynx','Pyrelynx','Sunfang Lynx'],
    look:'A lean, quick fire cat with orange fur striped in darker flame marks, tufted ears, bright yellow eyes and a tail tip that burns like a torch.',
    evoLooks:['Larger and more muscular, with flames running along its back like a mane and longer fangs.','A regal sun-cat with a blazing mane, glowing stripes and small embers trailing from its paws.']},
  magmite:{name:'Magmite',el:'pyre',rarity:'rare',body:'golem',c1:'#5A2A22',c2:'#FF6A2A',eye:'#FFD27A',hp:150,atk:15,spd:0.85,pattern:'runes',special:'Molten Slam',
    forms:['Magmite','Magmaul','Caldera Colossus'],
    look:'A squat golem of dark cooled magma with glowing orange cracks, a molten core in its chest and heavy rock fists that drip lava.',
    evoLooks:['Taller and broader, with lava spilling from its shoulders and a brighter core.','A towering volcano-shaped colossus with a caldera on its back that smokes and glows.']},
  hearthwyrm:{name:'Hearthwyrm',el:'pyre',rarity:'epic',body:'serpent',c1:'#A8321E',c2:'#FFB347',eye:'#FFF1B8',hp:140,atk:22,spd:1.1,tail:'flame',crown:true,special:'Hearthfire Coil',
    forms:['Hearthwyrm','Forgewyrm','Sunheart Wyrm'],
    look:'A coiled serpent of deep red scales with an ember-gold belly, a small crown of flame on its head and a burning tail tip.',
    evoLooks:['Longer and thicker, with flames licking along its spine and brighter scales.','A great fire serpent wrapped around a floating sun-orb, crowned with living flame.']},
  pyrrhax:{name:'Pyrrhax',el:'pyre',rarity:'legendary',body:'drake',c1:'#9C1E1E',c2:'#FF9A3C',eye:'#FFE08A',hp:176,atk:27,spd:1.05,horns:4,wings:'bat',tail:'flame',pattern:'runes',special:'Cataclysm Breath',
    forms:['Pyrrhax','Pyrrhax, Ashen Tyrant','Pyrrhax, World-Kiln'],
    look:'A fierce young fire dragon with crimson scales, glowing orange runes, four swept-back horns, leathery bat wings and a tail that ends in flame.',
    evoLooks:['A powerful dragon with ash-black armor plates, larger wings and smoke pouring from its jaws.','A colossal dragon whose chest glows like a furnace, with burning wings and a crown of horns.']},
  // ---------- Thorn ----------
  thistlekit:{name:'Thistlekit',el:'thorn',rarity:'rare',body:'beast',c1:'#5C8A3C',c2:'#D6E88A',eye:'#FFF6B0',hp:112,atk:17,spd:1.2,tail:'leaf',pattern:'spots',special:'Burr Barrage',
    forms:['Thistlekit','Thistlefox','Briarfox Matriarch'],
    look:'A small green fox with a fluffy tail shaped like a thistle flower, pale spots along its back and bright curious eyes.',
    evoLooks:['A sleek fox with thorny ruff fur and a larger flowering tail.','A graceful great fox with a tail of blooming thistles and a crown of leaves.']},
  barkbeak:{name:'Barkbeak',el:'thorn',rarity:'rare',body:'avian',c1:'#6B5236',c2:'#A7D46F',eye:'#FFE9A0',hp:118,atk:16,spd:1.05,pattern:'stripes',special:'Rootpeck',
    forms:['Barkbeak','Barkhoot','Elderbark Owl'],
    look:'A round owl whose feathers look like tree bark, with moss on its wing tips, a leafy crest and wide amber eyes.',
    evoLooks:['A larger owl with branch-like wing feathers and small flowers in its crest.','An ancient forest owl with antler-like branches, glowing moss and a cloak of leaves.']},
  grovewarden:{name:'Grovewarden',el:'thorn',rarity:'epic',body:'golem',c1:'#4A5E2E',c2:'#B6E07A',eye:'#EFFFB0',hp:155,atk:20,spd:0.9,pattern:'runes',spikes:true,special:'Wildwood Crush',
    forms:['Grovewarden','Grovekeeper','Heartwood Titan'],
    look:'A sturdy golem made of living wood and vines, with glowing green runes carved into its bark and small thorny branches on its shoulders.',
    evoLooks:['Taller, with thicker vines and flowering branches growing from its back.','A towering tree titan with a canopy of leaves on its shoulders and a glowing heartwood core.']},
  sylvarok:{name:'Sylvarok',el:'thorn',rarity:'legendary',body:'beast',c1:'#3E6B3A',c2:'#E4F2A8',eye:'#FFFBD6',hp:180,atk:26,spd:1.05,horns:6,tail:'leaf',pattern:'runes',special:'Call of the Wildwood',
    forms:['Sylvarok','Sylvarok, Grove King','Sylvarok, Heart of the Wild'],
    look:'A majestic forest stag with mossy green fur, huge antlers of living branches with small leaves, glowing runes on its flanks and a gentle, ancient gaze.',
    evoLooks:['Its antlers bloom with flowers and vines trail from them; its fur glows faintly.','A colossal spirit stag whose antlers form a whole tree canopy, with fireflies and petals swirling around it.']},
  // ---------- Tide ----------
  coralkin:{name:'Coralkin',el:'tide',rarity:'rare',body:'golem',c1:'#C8506A',c2:'#FFB8C6',eye:'#E8FBFF',hp:140,atk:15,spd:0.9,pattern:'spots',special:'Reef Barrier',
    forms:['Coralkin','Coralguard','Great Reef Sentinel'],
    look:'A small golem built from pink coral with barnacle spots, a glowing sea-blue eye slit and seaweed hanging from its arms.',
    evoLooks:['Bigger, with branching coral growing from its shoulders and small fish swimming around it.','A massive reef fortress with coral spires, sea anemones and a glowing pearl core.']},
  kelpmane:{name:'Kelpmane',el:'tide',rarity:'rare',body:'beast',c1:'#2E7D8C',c2:'#8FE0D0',eye:'#E6FFFA',hp:118,atk:17,spd:1.15,fins:true,tail:'fin',special:'Tidal Gallop',
    forms:['Kelpmane','Surfsteed','Tidal Charger'],
    look:'A small water horse with teal skin, a flowing mane of kelp, fin-shaped ears and a fish-fin tail.',
    evoLooks:['A graceful steed with a long kelp mane, fins on its legs and water splashing at its hooves.','A powerful charger made partly of water, with a crashing-wave mane and glowing blue markings.']},
  riptalon:{name:'Riptalon',el:'tide',rarity:'epic',body:'drake',c1:'#1F5E8C',c2:'#7FD8F2',eye:'#F0FCFF',hp:145,atk:22,spd:1.1,horns:2,wings:'feather',tail:'fin',special:'Riptide Dive',
    forms:['Riptalon','Riptalon Raider','Riptalon Stormtide'],
    look:'A sea drake with deep blue scales, a pale aqua belly, finned wings and a fish-fin tail.',
    evoLooks:['Larger, with sharper fins, coral horns and water streaming from its wings.','A sleek sea dragon trailing a whirlpool, with glowing blue markings and huge finned wings.']},
  thalassor:{name:'Thalassor',el:'tide',rarity:'legendary',body:'serpent',c1:'#16406E',c2:'#6FD0F5',eye:'#FFFFFF',hp:182,atk:26,spd:1.05,crown:true,tail:'fin',pattern:'runes',special:'Deep King\'s Tide',
    forms:['Thalassor','Thalassor, Deep King','Thalassor, Sovereign of Tides'],
    look:'A regal sea serpent with midnight-blue scales, glowing aqua runes, a crown of coral and pearls and wide fins.',
    evoLooks:['Longer and grander, with a flowing fin mane and rings of water circling it.','A colossal sea serpent crowned in pearls and coral, rising from a spiraling maelstrom.']},
  abyssarch:{name:'Abyssarch',el:'tide',rarity:'mythic',body:'serpent',c1:'#0E2447',c2:'#4FE0E6',eye:'#E8FFFF',hp:195,atk:29,spd:1.05,crown:true,tail:'fin',pattern:'runes',eyes:3,special:'Tide Eternal',
    forms:['Abyssarch','Abyssarch, Drowned Crown','Abyssarch, the Tide Eternal'],
    look:'An ancient abyssal leviathan with near-black scales lit by bioluminescent cyan runes, a jagged crown, and eyes like distant lanterns.',
    evoLooks:['Its body glows with rings of light and its crown grows taller, with deep-sea creatures circling it.','A world-sized leviathan wreathed in endless waves, crowned in light, with the ocean itself swirling around it.']},
  // ---------- Frost ----------
  snowmane:{name:'Snowmane',el:'frost',rarity:'rare',body:'beast',c1:'#A9C8DE',c2:'#FFFFFF',eye:'#BFEFFF',hp:115,atk:17,spd:1.2,tail:'spike',special:'Blizzard Howl',
    forms:['Snowmane','Snowfang','Winterwolf Alpha'],
    look:'A fluffy white arctic wolf pup with pale blue shading, icy blue eyes and small ice crystals on its tail tip.',
    evoLooks:['A strong wolf with a thick frosty mane and icicle fangs.','A huge alpha wolf with an ice-crystal mane, a frosted breath aura and glowing blue eyes.']},
  frostmote:{name:'Frostmote',el:'frost',rarity:'rare',body:'wisp',c1:'#6FB6D9',c2:'#E6FAFF',eye:'#FFFFFF',hp:100,atk:19,spd:1.2,eyes:1,special:'Hailstorm',
    forms:['Frostmote','Snowflurry','Aurora Wisp'],
    look:'A floating spirit made of swirling snowflakes, with a single big friendly eye and tiny icicle hands.',
    evoLooks:['A larger spirit trailing a blizzard, with glittering ice crystals orbiting it.','A shimmering spirit of the northern lights with three eyes and ribbons of aurora color.']},
  glacivore:{name:'Glacivore',el:'frost',rarity:'epic',body:'brute',c1:'#8FB3C9',c2:'#F2FBFF',eye:'#9FE6FF',hp:155,atk:21,spd:0.95,horns:2,spikes:true,special:'Avalanche Fist',
    forms:['Glacivore','Glaciermaw','Permafrost Behemoth'],
    look:'A hulking yeti-like beast with shaggy white-blue fur, two ice horns, icicle spikes on its back and huge fists.',
    evoLooks:['Bigger, with ice armor on its shoulders and frost breath.','A mountain-sized frost titan with glacier plates, a crown of ice and a blizzard swirling around it.']},
  rimedrake:{name:'Rimedrake',el:'frost',rarity:'epic',body:'drake',c1:'#5E8FB8',c2:'#DDF6FF',eye:'#FFFFFF',hp:140,atk:22,spd:1.1,horns:2,wings:'bat',tail:'spike',pattern:'spots',special:'Frozen Breath',
    forms:['Rimedrake','Rimewyvern','Hoarfrost Dragon'],
    look:'A young ice dragon with pale blue scales, frosty white spots, crystal horns, bat wings with icy membranes and a spiked tail.',
    evoLooks:['Larger, with icicles hanging from its wings and a frost cloud around its jaws.','A majestic ice dragon with crystalline wings, a glittering crown of horns and snow falling around it.']},
  glaciarch:{name:'Glaciarch',el:'frost',rarity:'legendary',body:'golem',c1:'#4E7FA6',c2:'#E0F8FF',eye:'#FFFFFF',hp:185,atk:25,spd:0.9,crown:true,pattern:'runes',wings:'feather',special:'Endless Winter',
    forms:['Glaciarch','Glaciarch, Frozen Throne','Glaciarch, the Endless Winter'],
    look:'A towering golem of ancient glacier ice with glowing white runes, a jagged ice crown and wings of frozen feathers.',
    evoLooks:['Its ice grows thicker and clearer, with a blizzard orbiting its crown.','A colossal frozen king with a cathedral of ice spires on its back and an eternal snowstorm around it.']},
  // ---------- Storm ----------
  sparkfox:{name:'Sparkfox',el:'storm',rarity:'rare',body:'beast',c1:'#E0B52E',c2:'#FFF6B8',eye:'#FFFFFF',hp:104,atk:18,spd:1.3,tail:'spike',pattern:'stripes',special:'Static Dash',
    forms:['Sparkfox','Voltfox','Thunderfox'],
    look:'A small yellow fox with zigzag lightning stripes, a spiky crackling tail and sparks jumping between its ears.',
    evoLooks:['Faster-looking and sleeker, with electricity arcing along its stripes.','A crackling storm fox made half of lightning, with a blazing electric tail.']},
  staticling:{name:'Staticling',el:'storm',rarity:'rare',body:'wisp',c1:'#6A5ACD',c2:'#FFF08A',eye:'#FFFFFF',hp:98,atk:19,spd:1.25,eyes:1,special:'Chain Spark',
    forms:['Staticling','Staticwisp','Storm Heart'],
    look:'A small purple storm-cloud spirit with yellow sparks, one bright eye and little lightning-bolt hands.',
    evoLooks:['A bigger thundercloud spirit with lightning arcing around it.','A roiling storm spirit with three eyes and a ring of lightning bolts.']},
  galvanox:{name:'Galvanox',el:'storm',rarity:'epic',body:'golem',c1:'#8C5A2B',c2:'#F2DC5D',eye:'#FFF6C2',hp:150,atk:21,spd:0.95,pattern:'runes',special:'Overload',
    forms:['Galvanox','Galvanox Mk II','Galvanox Tesla Titan'],
    look:'A copper-skinned golem wrapped in coils, with glowing yellow circuit-like runes and a crackling core.',
    evoLooks:['Larger, with lightning rods on its shoulders and brighter coils.','A towering storm engine with arcs of lightning between its shoulder spires.']},
  stormwyrm:{name:'Stormwyrm',el:'storm',rarity:'epic',body:'serpent',c1:'#3E3A7A',c2:'#E8D04A',eye:'#FFF6C2',hp:138,atk:23,spd:1.15,pattern:'stripes',tail:'spike',special:'Thunder Coil',
    forms:['Stormwyrm','Tempestwyrm','Skystorm Leviathan'],
    look:'A serpent of dark indigo scales with glowing yellow lightning stripes and a crackling spiked tail.',
    evoLooks:['Longer, with storm clouds trailing from its fins.','A sky serpent coiled through thunderclouds, lightning pouring off its body.']},
  fulgrax:{name:'Fulgrax',el:'storm',rarity:'legendary',body:'drake',c1:'#2F2A66',c2:'#FFE45C',eye:'#FFFFFF',hp:172,atk:28,spd:1.15,horns:4,wings:'bat',tail:'spike',pattern:'stripes',special:'Skybreaker Roar',
    forms:['Fulgrax','Fulgrax, Stormbringer','Fulgrax, Heart of the Tempest'],
    look:'A storm dragon with dark indigo scales, glowing yellow lightning stripes, four horns acting as lightning rods and wide bat wings.',
    evoLooks:['Lightning crackles between its horns and its wings are edged with storm clouds.','A colossal thunder dragon wreathed in a hurricane, lightning constantly striking around it.']},
  // ---------- Stone ----------
  cragbeak:{name:'Cragbeak',el:'stone',rarity:'rare',body:'avian',c1:'#7D6A55',c2:'#C9B28E',eye:'#FFB35C',hp:125,atk:17,spd:1.0,pattern:'spots',special:'Boulder Drop',
    forms:['Cragbeak','Crag Harrier','Mountain Roc'],
    look:'A sturdy bird with slate-grey stone feathers, pebble spots, a heavy stone beak and amber eyes.',
    evoLooks:['Larger, with rock-plate wings and a jagged crest.','A great mountain bird with cliff-like wings and crystals growing from its crest.']},
  pebblepaw:{name:'Pebblepaw',el:'stone',rarity:'rare',body:'beast',c1:'#8A7A64',c2:'#D8C8A8',eye:'#FFD28A',hp:130,atk:16,spd:1.0,tail:'spike',pattern:'spots',special:'Rockslide Rush',
    forms:['Pebblepaw','Bouldhound','Granite Warhound'],
    look:'A stocky dog-like pup with sandy stone skin, pebble spots and a stubby spiked tail.',
    evoLooks:['A strong hound with rock plates on its back and a boulder-like tail club.','A massive war hound armored in granite with crystal spikes along its spine.']},
  geodrake:{name:'Geodrake',el:'stone',rarity:'epic',body:'drake',c1:'#5E4E3E',c2:'#B28CFF',eye:'#FFE0A0',hp:152,atk:21,spd:0.95,horns:2,wings:'bat',tail:'spike',pattern:'spots',special:'Crystal Quake',
    forms:['Geodrake','Geowyvern','Amethyst Dragon'],
    look:'A stone dragon with rocky brown scales, purple crystal growths like geodes along its back, and heavy stone wings.',
    evoLooks:['More crystals erupt from its shoulders and wings.','A dragon of living geode, with a glittering amethyst crown and crystal wings.']},
  basaltusk:{name:'Basaltusk',el:'stone',rarity:'epic',body:'brute',c1:'#3E3A3A',c2:'#E0804A',eye:'#FFB35C',hp:160,atk:20,spd:0.85,horns:4,spikes:true,special:'Tectonic Charge',
    forms:['Basaltusk','Basaltusker','Obsidian Mammoth'],
    look:'A heavy beast of dark basalt with glowing orange cracks, four tusk-like horns and jagged rock spikes on its back.',
    evoLooks:['Bigger, with huge curved tusks and magma glowing in its cracks.','A colossal obsidian mammoth with volcanic vents on its back.']},
  montagrim:{name:'Montagrim',el:'stone',rarity:'legendary',body:'golem',c1:'#5A5046',c2:'#D8C8A8',eye:'#FFB35C',hp:195,atk:24,spd:0.85,crown:true,pattern:'runes',spikes:true,special:'Living Peak',
    forms:['Montagrim','Montagrim, Peak Warden','Montagrim, the Living Mountain'],
    look:'A giant golem shaped like a small mountain, with snow on its peaks, glowing amber runes and pine trees on its shoulders.',
    evoLooks:['Taller peaks and a waterfall pouring from one shoulder.','A true living mountain with clouds around its summit and a glowing core of molten amber.']},
  // ---------- Gale ----------
  gustfang:{name:'Gustfang',el:'gale',rarity:'rare',body:'beast',c1:'#6AB89A',c2:'#E6FFF2',eye:'#FFFFFF',hp:110,atk:18,spd:1.3,tail:'leaf',pattern:'stripes',special:'Slipstream Bite',
    forms:['Gustfang','Galefang','Cyclone Wolf'],
    look:'A lean mint-green wolf pup with swept-back wind-stripe fur, feathery ears and a tail that trails wisps of air.',
    evoLooks:['Faster-looking, with feather-like fur and wind currents swirling around its paws.','A sleek wind hound surrounded by a small cyclone, fur streaming like banners.']},
  cloudpuff:{name:'Cloudpuff',el:'gale',rarity:'rare',body:'wisp',c1:'#B8D8E6',c2:'#FFFFFF',eye:'#6FA8C0',hp:120,atk:15,spd:1.2,eyes:1,special:'Downdraft',
    forms:['Cloudpuff','Cumulus','Stormfront Spirit'],
    look:'A fluffy white cloud spirit with one sleepy eye and small puffy hands.',
    evoLooks:['A big billowing cloud with wind swirls around it.','A towering sky spirit with a wind crown and gusts streaming from its sides.']},
  cyclonyx:{name:'Cyclonyx',el:'gale',rarity:'epic',body:'avian',c1:'#3E8A6E',c2:'#D8FFEA',eye:'#FFFFFF',hp:136,atk:23,spd:1.25,pattern:'stripes',tail:'leaf',special:'Eye of the Cyclone',
    forms:['Cyclonyx','Cyclone Raptor','Hurricane Sovereign'],
    look:'A sharp-eyed raptor with deep green feathers, pale wind-stripe markings and long tail streamers.',
    evoLooks:['Larger, with wings that trail small whirlwinds.','A majestic storm raptor at the center of a spinning cyclone.']},
  skyreaver:{name:'Skyreaver',el:'gale',rarity:'epic',body:'drake',c1:'#4A9E8C',c2:'#E0FFF4',eye:'#FFFFFF',hp:140,atk:22,spd:1.2,horns:2,wings:'feather',tail:'leaf',special:'Razor Gale',
    forms:['Skyreaver','Skyreaver Wyvern','Skyreaver Zenith'],
    look:'A slim sky drake with jade scales, pale feathered wings and a leaf-shaped tail fin.',
    evoLooks:['Longer wings with feather blades and streaming wind trails.','A soaring sky dragon with four feathered wings and a halo of wind.']},
  zephyrion:{name:'Zephyrion',el:'gale',rarity:'legendary',body:'avian',c1:'#2E8A76',c2:'#F0FFF8',eye:'#FFFFFF',hp:170,atk:27,spd:1.3,crown:true,tail:'leaf',pattern:'runes',special:'High Winds',
    forms:['Zephyrion','Zephyrion, Sky Lord','Zephyrion, Lord of the High Winds'],
    look:'A regal wind bird with jade and white feathers, glowing wind runes, a crest like a crown and long flowing tail feathers.',
    evoLooks:['Its wings lengthen and its tail feathers ripple like ribbons of wind.','A colossal sky sovereign whose wings stir whole cloud banks, crowned with swirling wind.']},
  // ---------- Radiant ----------
  halomote:{name:'Halomote',el:'radiant',rarity:'rare',body:'wisp',c1:'#E8C45A',c2:'#FFF8DD',eye:'#FFFFFF',hp:110,atk:17,spd:1.15,eyes:1,crown:true,special:'Halo Pulse',
    forms:['Halomote','Halowisp','Sanctum Light'],
    look:'A small golden light spirit with a glowing halo above it, one kind eye and soft glowing hands.',
    evoLooks:['A brighter spirit with a double halo and glittering motes.','A radiant guardian spirit with three eyes and wings of light.']},
  sunfinch:{name:'Sunfinch',el:'radiant',rarity:'rare',body:'avian',c1:'#F0C04A',c2:'#FFF6D0',eye:'#FFFFFF',hp:104,atk:18,spd:1.25,pattern:'spots',special:'Dawn Chorus',
    forms:['Sunfinch','Dawnlark','Solar Phoenix'],
    look:'A round golden songbird with sun-spot markings, a sunburst crest and warm glowing feathers.',
    evoLooks:['A graceful lark with long golden tail feathers and a brighter crest.','A radiant sun bird with blazing golden wings and a halo of light.']},
  dawnwarden:{name:'Dawnwarden',el:'radiant',rarity:'epic',body:'golem',c1:'#C8A04A',c2:'#FFF3C4',eye:'#FFFFFF',hp:158,atk:20,spd:0.95,pattern:'runes',wings:'feather',special:'Aegis of Dawn',
    forms:['Dawnwarden','Dawnbastion','Sunforged Sentinel'],
    look:'A golden stone guardian with white glowing runes, small feathered wings and a radiant core shaped like a sunrise.',
    evoLooks:['Larger wings and polished gold armor with brighter runes.','A towering sun sentinel with great wings of light and a blazing halo.']},
  aurelion:{name:'Aurelion',el:'radiant',rarity:'legendary',body:'beast',c1:'#D9A441',c2:'#FFF1C4',eye:'#FFFFFF',hp:178,atk:27,spd:1.1,crown:true,tail:'flame',pattern:'runes',special:'Solar Roar',
    forms:['Aurelion','Aurelion, Sunmane','Aurelion, King of Dawn'],
    look:'A noble golden lion with a mane that glows like sunlight, white runes on its flanks and a small halo crown.',
    evoLooks:['Its mane burns brighter like a corona and light streams from its paws.','A colossal sun lion with a mane of pure light and a crown of sunrays.']},
  luminarch:{name:'Luminarch',el:'radiant',rarity:'mythic',body:'drake',c1:'#F2D27A',c2:'#FFFFFF',eye:'#FFFFFF',hp:190,atk:30,spd:1.1,horns:4,wings:'feather',tail:'flame',pattern:'runes',crown:true,special:'The First Light',
    forms:['Luminarch','Luminarch, Dawnbringer','Luminarch, the First Light'],
    look:'A radiant dragon of pale gold and white, with four horns, great feathered wings of light, glowing runes and a crown of sunrays.',
    evoLooks:['Six wings of light and a brighter crown; its scales shine like polished gold.','A celestial dragon made of pure light, with a sun behind it and rays pouring from its wings.']},
  // ---------- Umbral ----------
  gloomfang:{name:'Gloomfang',el:'umbral',rarity:'rare',body:'beast',c1:'#3A2A5E',c2:'#A07AE0',eye:'#E6D6FF',hp:112,atk:19,spd:1.2,tail:'spike',pattern:'stripes',special:'Shadow Lunge',
    forms:['Gloomfang','Gloomhound','Nightmare Warg'],
    look:'A shadowy wolf pup with dark violet fur, faint purple stripes, glowing lavender eyes and wisps of shadow at its paws.',
    evoLooks:['A larger wolf with a smoky shadow mane and glowing fangs.','A huge nightmare wolf whose body fades into smoke at the edges.']},
  shadelet:{name:'Shadelet',el:'umbral',rarity:'rare',body:'drake',c1:'#2E2048',c2:'#8C5AD8',eye:'#E6D6FF',hp:108,atk:19,spd:1.15,horns:2,wings:'bat',tail:'spike',special:'Umbral Nip',
    forms:['Shadelet','Shadewyvern','Umbral Wyrmlord'],
    look:'A small shadow dragon hatchling with dark purple scales, tiny bat wings and big glowing lavender eyes.',
    evoLooks:['A sleek shadow wyvern with smoky wings.','A menacing shadow dragon whose wings dissolve into darkness.']},
  nightveil:{name:'Nightveil',el:'umbral',rarity:'epic',body:'avian',c1:'#241A38',c2:'#9A6BD6',eye:'#F2E6FF',hp:138,atk:23,spd:1.2,pattern:'spots',tail:'leaf',special:'Veil of Night',
    forms:['Nightveil','Nightveil Raven','Eclipse Raven'],
    look:'A dark raven with violet-black feathers speckled like stars, long tail feathers and piercing lilac eyes.',
    evoLooks:['Larger, with feathers that trail smoke and more starry spots.','A great raven whose wings hold a starry night sky, with an eclipse halo behind it.']},
  umbrath:{name:'Umbrath',el:'umbral',rarity:'legendary',body:'drake',c1:'#1E1430',c2:'#B58BF0',eye:'#FFFFFF',hp:175,atk:28,spd:1.1,horns:4,wings:'bat',tail:'spike',pattern:'runes',crown:true,special:'Hollow Crown',
    forms:['Umbrath','Umbrath, Hollow King','Umbrath, Night Eternal'],
    look:'A shadow dragon with near-black scales, glowing violet runes, a jagged crown of horns and tattered bat wings.',
    evoLooks:['Its wings become smoke and its crown glows violet.','A colossal shadow dragon whose body is a starless void outlined in violet light.']},
  nihilarch:{name:'Nihilarch',el:'umbral',rarity:'mythic',body:'serpent',c1:'#120C1E',c2:'#C08CFF',eye:'#FFFFFF',hp:192,atk:31,spd:1.1,crown:true,pattern:'runes',eyes:3,tail:'spike',special:'Devourer of Stars',
    forms:['Nihilarch','Nihilarch, Starless','Nihilarch, Devourer of Stars'],
    look:'A cosmic void serpent with a body like the night sky, faint star specks, violet runes and a crown of dark crystal.',
    evoLooks:['Galaxies swirl along its body and its crown grows into a ring of dark stars.','A world-eating serpent coiled around a collapsing star, crowned with an eclipse.']},
};
